config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end
  
  get 'groups/index'
  root 'polls#index'
  

  #devise_for :users
  
  get 'poll/new' => 'polls#new'

  
  
  #root to: 'polls#index'



  resources :polls do
    resources :lists
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  accepts_nested_attributes_for :group_users
end

app/models/group_poll.rb
class GroupPoll < ApplicationRecord
  belongs_to :poll
  belongs_to :group
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user 
  belongs_to :group
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :poll 
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :lists ,dependent: :destroy#, inverse_of: :poll
  has_many :poll_users ,dependent: :destroy
  has_many :users, through: :poll_users
  accepts_nested_attributes_for :lists, allow_destroy: true
  accepts_nested_attributes_for :users, allow_destroy: true

  validates :title, presence: true,length: { in: 1..50 } 
  validates :started_at, presence: true
  validates :ended_at, presence: true
  validate :start_check
  validate :before_check

  def start_check
    if started_at.present? && started_at < DateTime.now
      errors.add(:started_at, ": 過去の日付は使用できません")
    end
  end
  
  def before_check
    if ended_at.present? && ended_at < started_at
      errors.add(:ended_at, ": 開始時間より過去の日付は使用できません")
    end
  end


end

app/models/poll_user.rb
class PollUser < ApplicationRecord
  belongs_to :poll
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :poll_users,dependent: :destroy
  has_many :polls, through: :poll_users

  accepts_nested_attributes_for :group_users,allow_destroy: true
  accepts_nested_attributes_for :poll_users,allow_destroy: true


  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :confirmable, :lockable, :timeoutable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
    
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def update
    @poll = Poll.find(params[:poll_id])
    @list = List.find(params[:id])
    @test = PollUser.new
  
    if @poll.users === []
      logger.debug('テスト2') 
      @test.poll_id = @list.poll_id
      @test.user_id = current_user.id
      @test.save
    end
  
    @poll.users.each do |u|
      if u.id === current_user.id
        logger.debug('テスト1')  
        flash[:alert] ="投票は一人一票までです" 
        redirect_to  poll_path(@list.poll_id)
        return  
        
      else
        logger.debug('テストyes')  
        @test.poll_id = @list.poll_id
        @test.user_id = current_user.id
        @test.save
      end
    end
  
    @list.count = @list.count+1
    @list.save!

    redirect_to  poll_path(@list.poll_id)

    # poll = current_user.polls.build do |t|
      
    #   t.title = @poll.title
    #   t.started_at  = @poll.started_at
    #   t.ended_at = @poll.ended_at
    # end
    # if @list.save && @poll.save
    #   render :json => current_user.polls
    # end

  end

  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.where("ended_at > ?", DateTime.now)
  end

  def show
    @poll = Poll.find(params[:id])
    @lists = @poll.lists
  end

  def new
    @poll = Poll.new
    @poll.lists.build
  end

  def create
    @poll = Poll.create(poll_params)
    @poll.lists.build
    redirect_to  '/polls'

    #こう書くべきだけど余分にlistできてしまう
    # @poll = Poll.new(poll_params)
    # @poll.lists.build
    # if @poll.save
    #   redirect_to  '/polls'
    # else
    #   render 'new'
    # end
  end


  def destroy
    poll = Poll.find(params[:id])
    if poll.users
      poll.poll_users.destroy 
    end
    Poll.find(params[:id]).destroy
    redirect_to '/'
  end



  private
  def poll_params
    params.require(:poll).permit(:title,:description,:started_at,:ended_at,lists_attributes:[:text, :poll_id, ])
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<h1>Groups#index</h1>
<p>Find me in app/views/groups/index.html.erb</p>

<% @groups.each do |g| %>
<p><%= g.name %></p>
<p><%= g.description %></p>
<% end %>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>

app/views/polls/_list_fields.html.erb
<div class='nested-fields'>
  <%= f.label :text,'項目' %>
  <%= f.text_field :text ,class: "form-control"%>

  <%= link_to_remove_association '削除', f %>

</div>

app/views/polls/index.html.erb
<% if user_signed_in? %>

<h2>投票箱一覧</h2>
<p class="nomal-button"><%= link_to '投票箱つくる', poll_new_path %></p>
<div class="polls">
  <% @polls.each do |poll| %>
  <div class="poll">
    <h3><%= poll.title %></h3>
    <p><%= poll.description %></p>
    <span><%= poll.started_at.strftime("%m月%d日 %H:%M") %></span>
    <span>～</span>
    <span><%= poll.ended_at.strftime("%m月%d日 %H:%M") %></span>

    <% poll.lists.each do |list| %>
    <ul>
      <li><%= list.text %></li>
    </ul>

    <% end %>
    <p class="poll-button"><%= link_to '投票する', poll_path(poll.id) %></p>
  </div>
  <% end %>
</div>
<% else %>
<p>ログインしてください。</p>
<% end %>

app/views/polls/new.html.erb
<% if user_signed_in? %>
<h1>投票箱新規作成</h1>
<%= form_with(model: @poll,local: true) do |f| %>
<% @poll.errors.full_messages.each do |message| %>
<p><%= message %></p>
<% end %>
<%= f.label :title,'投票箱名' %>
<%= f.text_field :title,class: "form-control" %><br />

<%= f.label :title,'概要' %>
<%= f.text_field :description,class: "form-control" %><br />

<%= f.label :started_at,'開始時間' %>
<%= f.datetime_field :started_at,class: "form-control" %><br />

<%= f.label :ended_at,'終了時間' %>
<%= f.datetime_field :ended_at,class: "form-control" %><br />

<%= f.fields_for :lists do |li| %>
<%= render 'list_fields', f: li %>
<% end %>
<div class="links">
  <%= link_to_add_association '追加', f, :lists %>
</div>


<%= f.submit '作成', class:"btn btn-primary" %>
<%= link_to "Back", :back %>
<% end %>

<% end %>

app/views/polls/show.html.erb
<% if user_signed_in? %>
<div class="pollBox">
  <h2><%= @poll.title %></h2>
  <p><%= @poll.description %></p>
  <% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>

  <ul class="polling">
    <% @poll.lists.each do |list| %>
    <li>
      <p><%= list.text %>&emsp;<span><%= list.count %>票</span></p>
      <%= button_to "投票する", poll_list_path(list.poll_id, list.id),:class=>'poll-go-button', method: :put ,data: {confirm: "投票は一人一票までですが投票しますか？"}%>
    </li>
    <% end %>
  </ul>
</div>
<p><%= button_to "削除", poll_path(@poll.id), method: :delete ,:class=>'delete-button' %></p>
<p><%= link_to  "一覧に戻る" , '/' %></p>

<% else %>
<p>ログインしてください。</p>

<% end %>